# Handover notes - Oct 2023

Summary of package changes, both complete and in progress, with notes and ideas
on future directions and priorities. 

## Changelog

- Restructuring
  - main.R contains the primary entrypoint wrapper functions
  - three types of function groups
    - check
      - checking terms etc
      - atm `check_fields()` function is the main entry point
    - modify
      - I thought this would be useful but I haven't decided if this is
        necessary yet. It might make more sense to have modifying functions
        grouped with their associated check, as I have done with
        `check_data_unique.R`. This way, groups of functions can continue to be
        separated out into their own check_* files if they become too large
        within the umbrella files `check_data_fields.R` and
        `check_data_values.R`
      - But `modify_*` files / functions would be useful for functions that are
        non specific and can be used across multiple checks
    - build
- EML creation fixed
  - Using `build_eml()` which is a slightly purpose modified version of the
    function from the EML package
    - The input markdown template is first converted to docbook format, which is
      an XML schema
    - It is then read into R as an XML object
    - The `xml2` package is used to interact with the object, and extract
      elements of text
    - The extracted text is converted into a list format
    - The list is then used to build a valid EML object, using the
      `EML::eml$eml` function
  - removed the rename to camel case function
    - i don't think its a useful component, because if your column names already
    don't match dwc terms, in most cases they still won't match after camel
    casing. And most of the fixing of column names in galaxias will be through a
    lookup table. So having columns renamed automatically to camel case will
    break a lookup table. 
    - If you did have columns that are named correctly but not in camel case, I
    think its something you would fix yourself, just one line of code
- Packages
  - crayon is superseded by cli, so I've changed to cli
  - EML package added
  - stringdist packaged added 
- Validation
  - eventDate
    - just a couple of quick proof concept functions 
    - I'm using "valid" according to https://dwc.tdwg.org/terms/#dwc:eventDate
    and their accepted "formats" for eventDate, even though they are not
    actually valid ISO 8601 which makes it difficult to validate things that
    don't fit this weird unstandardised format, without special handling for
    every edge. So the main implementation is a regex taken from what gbif
    seemed to use, found on github.
 
 ## Style

- I changed to read.csv instead of read_csv, and using data frames instead of
tibble, since i don't have experience using tibbles before, and apparently
tibbles have some different behaviour if using base R subsetting, which I use
  - [] substiution always returns a tibble from a tibble, which is different to
  base data frame behaviour
- I call external functions explicitly in most cases, like `cli::col_blue()`,
  rather than importFrom, esp. if its just a few calls, and mainly just use
  importFrom if its a call used a lot
  - it makes a code base easier to read and maintain imo
- I use VScode with auto formatting to wrap lines at 80 characters
  - stylistic, just mentioning as an FYI in case you want to keep to that in the future
  - Not sure how to do it in Rstudio, probably there is a package
  - Also as an FYI as to why some text outputs are wrapped in `paste0()`, its to break text in the code without breaking the output

## Misc. notes and todos

These were existing notes and todos within the package that I've removed and
collated here:
- From `README`: 
  - auto-detect field headings and data types (`{janitor}`, `{lubridate}` etc) IN PROGRESS
- ask sensible questions to fill unavailable columns (e.g. spatial resolution)