---
title: "Structure of Darwin Core Archives"
author: "Martin Westgate"
date: '2024-01-05'
output:
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Structure of Darwin Core Archives}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
Darwin Core (DwC) is a standardised framework used for compiling biodiversity
data, and is maintained by the Biodiversity Information Standards group
(https://www.tdwg.org). As a data standard, DwC facilitates the sharing and use
of open-access biodiversity data, and is used by GBIF and it's node member
organisations. 

In practice, the DwC standards and terms are used to create a single,
self-contained dataset, known as a Darwin Core Archive (DwC-A). The format of
this archive is a `ZIP` file containing text files of data and metadata, and
represents the fundamental unit required to share DwC compliant biodiversity
data.

A DwC-A can contain a range of different files, but there are three main files that are required:

- A data core: A core dataset, such as an Occurrence or Event core
- `eml.xml`: A resource metadata file describing the dataset, in the Ecological
  Metadata Language (EML) format
- `meta.xml`: A metadata file describing the structure and relationships of
files within the archive
