---
title: "EML"
author: "Fonti Kar"
date: "2023-05-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages

```{r}
library(tidyverse)
library(EML)
library(here)
library(stringr)
```

#### .md into R

```{r}
scan_output <- scan(here("doc/westerband_template.md"),
                    what = "character", 
                    sep = "\n", 
                    blank.lines.skip = FALSE)

str(scan_output)

# This format might be better since not every word is separated as a string
rl_output <- readLines(con = here("doc/westerband_template.md")) 

str(rl_output)

# Make as tibble
rl_df <- tibble(input = rl_output)

# Count the # at the start of the string
# Testing the regex pattern
str_subset(rl_df$input, regex("^#"))

# Create grouping variable
rl_df <- rl_df |>
  mutate(group_id = str_detect(input, regex("^#")) |> cumsum())

# Split by group id for now to have a look
split(rl_df, f = rl_df$group_id)

# Create a function to do this
join_user_text <- function(group_df){
  group_df |> 
  slice(2:nrow(group_df)) |>  # Take anything below the 1st row
  filter(! input == "") |>  # Exclude the empty elements of input 
  pull(input) |>  # Isolate column as vector
  paste(collapse="")  #  Join strings
}

# Mapping across the group_id
rl_nest <- rl_df |> 
  nest(text = input) |> 
  mutate(joined_str = map(text,
                          ~join_user_text(.x)))

# Create header variable to denote the section the text is from
clean_header <- function(group_df){
  group_df |> 
    slice(1) |> 
    pull(input) |> 
    trimws("both") |> 
    str_replace(pattern = "^#{1,}", replacement = "") |> 
    str_replace(pattern = "\\+$|\\*$", replacement = "") |> 
    trimws("both") 
}

# Unnest 
rl_wrangled <- rl_nest |> 
  mutate(header = map(text,
                      ~clean_header(.x))) |> 
  select(group_id, header, joined_str,  text) |> 
  unnest(cols = c(header, joined_str)) |> 
  print(n = 30)
```

### md content into list
```{r}
x <- rl_wrangled |> 
  select(joined_str)

# Convert into list
list <- as.list(x) |> list_transpose() 

# Set names to match the template
named_list <- set_names(list, rl_wrangled$header)
```

# Break up name

```{r}
extract_name <- function(data, var = "Name", which){
  if(which == "first"){
  name <- data |> 
  filter(header == var) |> 
  pull(text) |> 
  word(1)
  }
  
  if(which == "last"){
  name <- data |> 
  filter(header == var) |> 
  pull(text) |> 
  word(2)
  }
  
  return(name)
}

extract_name(rl_wrangled, which = "first")

# Extract name from a ls
extract_name_ls <- function(list, var = "Name", which){
  if(which == "first"){
  name <- list |> 
    pluck(var) |> 
    pluck("text") |> 
    word(1)
  }
  
  if(which == "last"){
  name <- list |> 
    pluck(var) |> 
    pluck("text") |> 
    word(2)
  }
  
  return(name)
}
```

# Overwrite template's Title and Name with text from template

```{r}
# Mini user text
data <- tibble(header = c("Title", "Name"),
               text = c("Australia-wide photosynthetic trait dataset", 
                        "Andrea Westerband"))

# Mini eml
eml <- list(
  dataset = list(
    title = "Dataset Name",
    contact = list(
      individualName = list(
        givenName = "Jay",
        surName = "Citizen"
      )
    )
  )
)

# Turn user text to list
data_ls <- data |> 
  select(text) |> 
  as.list() |> 
  transpose()

# Set names to match the template
named_data_ls <- set_names(data_ls, data$header)

# Break up name into first and last name
extract_name_ls(named_data_ls, which = "first")
extract_name_ls(named_data_ls, which = "last")


# Assign to eml to update names field
updated_eml <- list_modify(eml, dataset = list(
  contact = list(
  individualName = list(
    givenName = extract_name_ls(named_data_ls, which = "first"), 
    surName = extract_name_ls(named_data_ls, which = "last")
  )
)
)
)

# Assign to em to update title field 
title_updated_eml <- list_modify(updated_eml, dataset = list(title = named_data_ls$Title$text))

# Write into xml
write_eml(title_updated_eml, "output/eml/updated.xml")
```

## Add systems attribute

```{r}
library(xml2)

updated_xml <- read_xml("output/eml/updated.xml")

html_structure(updated_xml)

xml_attr(updated_xml, "system") 
ns <- xml_ns(updated_xml) 

xml_set_attr(updated_xml, "system", value = "ALA-Registry")

xml_attr(updated_xml, "system", ns)

EML::as_emld(updated_xml)

write_eml(EML::as_emld(updated_xml), "output/eml/attr_updated.xml")

```

## Add scope attribute

```{r}
xml_set_attr(updated_xml, "scope", value = "system")

EML::as_emld(updated_xml)
```


