---
title: "metadata"
author: "Fonti Kar"
date: "2023-04-30"
output: html_document
---

# ALA Dataset Metadata

Write WITHIN/INSIDE the chunk blocks
Currently made for mandatory fields only, template found [here](https://support.ala.org.au/support/solutions/articles/6000261427-sharing-a-dataset-with-the-ala#minimum-fields)

## Data Resource

```{r, Title}
Australia-wide photosynthetic trait dataset
```

```{r, URL}
https://doi.org/10.5061/dryad.j9kd51cgr
```

## Description

```{r, Public short description}
Data collection/generation of data: Light-saturated rates of photosynthesis were measured at ambient CO2 levels using a portable gas exchange system. Stomatal conductance to water vapor and Ci:Ca correspond to light-saturated rates of photosynthesis. Carboxylation capacity, Vcmax, was estimated via the one-point method when it was not provided from A-ci curves. Concentrations of leaf nitrogen and phosphorus were measured using an elemental analyzer.  LMA was measured by dividing the leaf dry mass by the surface area of a fresh leaf. 

Climate data were extracted for each site from the eMAST data project. Soil data were measured for a subset of sites and extracted from the CSIRO SoilGrids for the remaining sites. 

Data processing: Raw data were used to calculate species means for all sites, which were then compiled to produce one data file. This was done using RStudio Version 1.3.959.

Environmental/experimental conditions: All data were collected on native plant species growing under natural conditions in the field. 

Describe any quality-assurance procedures performed on the data: Ci:Ca values less than 0 or greater than 1 were excluded, as were stomatal conductance values greater than 3000 millimol per square meter per second. Vcmax 25 values greater than 500 micromol CO2 per square meter per second were also excluded from the final analysis.
```

## Citation and Rights

```{r, Citation}
Westerband, Andrea et al. (2022), Australia-wide photosynthetic trait dataset, Dryad, Dataset, https://doi.org/10.5061/dryad.j9kd51cgr
```

```{r, Creator}
Firstname Lastname
```

CC0, CC-BY, CC-BY-NC preferred

```{r, License}
CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
```

## Primary Contact(s) 

```{r, Name}
Firstname Lastname
```

```{r, Email}
youremail@email.com
```


