#' ALA eml.xml template
#'
#' @return
#' @keywords internal
#'
#' @examples 
#' eml <- eml_template_ls()
eml_template_ls <- function(){
  # This is the set structure based on provided example of an eml.xml
  list(
    dataset = list(
      alternateIdentifier = "48458dk392-dfkal-b7e4-609",
      alternateIdentifier = "https://collections-test.ala.org.au/public/show/dr860275602765",
      title = "Dataset Name",
      creator = list(
        organizationName = "Organisation Name",
        metadataProvider = "Organisation Name"
      ),
      associatedParty = list(
        organizationName = "Atlas of Living Australia",
        address = list(
          deliveryPoint = "CSIRO Ecosystems Services",
          city = "Canberra",
          administrativeArea = "ACT",
          postalCode = "2601",
          country = "Australia"
        ) ,
        role = "distributor"
      ),
      pubDate = "2022-06-21",
      language = "English",
      abstract = "And then bandicoot from case in point. Lilly pilly cane toad kingfisher. Tasmanian devil lemon myrtle blue-ringed octopus.",
      intellectualRights = list(
        citetitle = "Creative Commons Attribution 4.0 International (CC-BY 4.0)"
      ),
      distribution =list(
        online = ""
      ),
      coverage = "",
      purpose = "",
      contact = list(
        individualName = list(
          givenName = "Jay",
          surName = "Citizen"
        )
      ),
      methods = ""
    ),
    additionalMetadata = list(
      metadata = list(
        gbif = list(
          dateStamp = "2022-06-21T04:45:31",
          hierarchyLevel = "dataset",
          resourceLogoUrl = "https://collections-test.ala.org.au/data/dataProvider/test.png</resourceLogoUrl"
        )
      )
    )
  )
}

#' Extract first or last name from $Name field
#'
#' @param list 
#' @param var 
#' @param which 
#'
#' @return
#' @export
#'
#' @examples 
#' 
#' convert_md_tibble_to_list(metadata_tibble) |> extract_name_from_ls(which = "last")
extract_name_from_ls <- function(list, var = "Name", which){
  if(which == "first"){
    name <- list |> 
      pluck(var) |> 
      word(1)
  }
  
  if(which == "last"){
    name <- list |> 
      pluck(var) |> 
      word(2)
  }
  
  return(name)
  
  # TODO: Option to take name from Creator if Name is not supplied, option to take first full name if multiple names are supplied
}


#' Update Name Field
#'
#' @param template ALA template structure generated by `eml_template_ls`
#' @param metadata_ls Metadata list generated by `convert_md_tibble_to_list`
#'
#' @return updated nested list with updated field
#' @export
#'
#' @examples
update_names <- function(template, metadata_ls){
  template_firstnm <- assign_in(template, c("dataset", "contact", "individualName", "givenName"), 
                                extract_name_from_ls(metadata_ls, which = "first"))
  
  template_names_updated <- assign_in(template_firstnm, c("dataset", "contact", "individualName", "surName"), 
                                      extract_name_from_ls(metadata_ls, which = "last"))
  
  return(template_names_updated)
  
  # TODO: Option to take name from Creator if Name is not supplied, option to take first full name if multiple names are supplied
}

#' Update Title field
#'
#'@inheritParams update_names

update_title<- function(template, metadata_ls){
  template_title <- assign_in(template, c("dataset", "title"), 
                              metadata_ls$Title)
  
  return(template_title)
  
  # TODO: Expand function to have argument denoting which field needs to be updated, then create a big switch function, changing depending on specified field
}
