#' Update Name Field in list template
#'
#' @param template ALA template structure generated by `eml_template_ls`
#' @param metadata_ls Metadata list generated by `convert_md_tibble_to_list`
#'
#' @return updated nested list with updated field
#' @importFrom purrr assign_in
#' @keywords internal
#'
#' @examples
#' eml <- eml_template_ls()
#' eml
#' update_names(eml,metadata_ls)

update_names <- function(template, metadata_ls){
  template_firstnm <- assign_in(template, c("dataset", "contact", "individualName", "givenName"), 
                                extract_name_from_ls(metadata_ls, which = "first"))
  
  template_names_updated <- assign_in(template_firstnm, c("dataset", "contact", "individualName", "surName"), 
                                      extract_name_from_ls(metadata_ls, which = "last"))
  
  return(template_names_updated)
  
  # TODO: Option to take name from Creator if Name is not supplied, option to take first full name if multiple names are supplied
  # Need to think about names with more than 3 words
  # The nested structure of each field is fixed, so we can either have a look up table of character strings
  # denoting what field is updated using 'assign_in' (e.g. tibble(givenName = c("dataset", "contact", "individualName", "givenName")) and these are called within a switch function
  # Possible solution and store this in sysdata
  # tibble::enframe(list('first_name'= c("dataset", "contact","individualName", "givenName"),
  #                      'last_name'= c( "dataset", "contact", "individualName", "surName")), 'md_field', 'str') |> 
  #   pluck("str", 1) 
  
}

#' Update Title field in list template
#'
#'@inheritParams update_names
#' @examples
#' eml <- eml_template_ls()
#' eml
#' update_title(eml,metadata_ls)

update_title<- function(template, metadata_ls){
  template_title <- assign_in(template, c("dataset", "title"), 
                              metadata_ls$Title)
  
  return(template_title)
  
  # TODO: Expand function to have argument denoting which field needs to be updated, then create a big switch function, changing depending on specified field
}